### ISSUE TITLE
Real time status updates while loading data dump file

### ISSUE THREAD

**Issue by Alexey-ebi** [cnr-ibba/IMAGE-InjectTool#14]
**Is your feature request related to a problem? Please describe.**
Real time status updates, no need to refresh page. For Ale’s data, loading status has been there for at least about two minutes. Give up waiting and play around, the submission list indicates loaded status. Probably the loading status has not been updated in time.

**Describe the solution you'd like**
We could use django-channels to send messages using websockets

**Describe alternatives you've considered**
Automatic page reload

**Additional context**
Required steps:
- [x] add support for django channels
- [x] adding tests for django channels  
- [x] mocking async calls in unittest (no call to asgi server during tests - no status update for record in InjectTool database)
- [ ] write a few words using sphinx for django channels (aim, how it works...)

**Comment by bunop** [comment]
Required steps:
- [x] add support for django channels
- [x] adding tests for django channels  
- [ ] mocking async calls in unittest (no call to asgi server during tests - no status update for record in InjectTool database)
- [ ] write a few words using sphinx for django channels (aim, how it works...)

**Comment by bunop** [comment]
Shinx documentation about django channels (aim, how it works...) will be added within another issue
