### ISSUE TITLE
Inject tool validation summary page

### ISSUE THREAD

**Issue by Alexey-ebi** [cnr-ibba/IMAGE-InjectTool#15]
**Is your feature request related to a problem? Please describe.**
Validation summary (could combine with submission summary)

**Describe the solution you'd like**
 - How many unknown, pass, warning, and error
 - If possible, what is the most occurred error, which may lead to batch correction, e.g. add decimal degrees to the coordinate as units
- Validation summary is static, could be calculated after validation and will remain the same until data changes
- Should be modeled as a `validation.models` class 
- Should use the [IMAGE-ValidationTool](https://github.com/cnr-ibba/IMAGE-ValidationTool) `image_validation.ValidationResult.ValidationResultColumn` to get information againt the most attribute failing
- Should have a dedicated page (not a record in `SubmissionDetailView`) to represent data
- Ideally we need to point this page with edit pages, or for the most common errors to bulk update, as described in #16 

**Describe alternatives you've considered**
It could start with a descriptive record. Could add other functionalities with time. We could decide a minimal set of features of such isse for [first milestone](https://github.com/cnr-ibba/IMAGE-InjectTool/milestone/1)

**Additional context**
Steps required:
- [x] Refactor `validation.helpers.ValidationSummary` using appropriate method
- [x] Define a validation status View
- [x] Define models for validation reports
- [x] prepare report after validation, as a part of validation (validation is not finished before report)
- [x] test code for pages and methods defined
- [x] Verify validation summary within *reload submission* condition
- [x] Update all-count when validating submission
- [x] Small refactoring to improve code readability

**Comment by Alexey-ebi** [comment]
I think that we still should have information about validation in SubmissionDetailedView and from there we could have a link to validation summary page.
So it could be:
N. of Animals                         26 (26 with issues in <a href="link_to_validation_summary">validation</a>)

**Comment by bunop** [comment]
Agree. But we need to discuss how (when) this number is calculated

**Comment by bunop** [comment]
Another consideration: this number could change (hopefully in better) after validation is finished. Should this message has to be submitted with the real time updates?

**Comment by Alexey-ebi** [comment]
Yes, sure. I am working on it right now!

**Comment by bunop** [comment]
Remember that this number is calculated on the fly when the page is loaded. Since it never changes after the validation, could be calculated once and stored somewhere. While doing this you could send the message as you did for the status and submission message. This is one thing we have to discuss.

**Comment by wizardfan** [comment]
> Since it never changes after the validation
 
Only true when validation can only be called manually (i.e. clicking the validate button)

A related question: validate all records or only records have been changed? (after uploading a data file, all records are actually changed from not-existing to some value) @bunop

**Comment by bunop** [comment]
If validation is called by admin or with a periodic task, it will apply all the stuff executed when clicking validation (since the button call a task in background), report included. They are not different in concepts.

Validation is called on all objects: only modified objects which pass validation could be submitted, as defined [here](https://github.com/cnr-ibba/IMAGE-InjectTool/blob/18ab59b09317fc1c9b76dda168f136e0434d769a/django-data/image/validation/tasks.py#L359). Submitted objects which pass validation will keep the same status

**Comment by bunop** [comment]
And a new object (after loading) need to be validated before submission, as described by [common statuses](https://www.wp5image.eu/image/docs/modules/common.html#common-statuses)
