### ISSUE TITLE
Batch submission to Biosamples

### ISSUE THREAD

**Issue by bunop** [cnr-ibba/IMAGE-InjectTool#32]
**Is your feature request related to a problem? Please describe.**
Submitting to Biosamples a lot of data within a single submission using [pyUSIrest](https://pypi.org/project/pyUSIrest/) is not so performant, because first all data are stored in memory as described in cnr-ibba/pyUSIrest#3, and then a big submission could imply overheads on USI servers.

**Describe the solution you'd like**
Submission to biosample should occur in batches, letting InjectTool to deal with all the stuff. From the user point of view, there will be no significant changes on the UI. This batch submission can also be parallelized using celery `chords` which could let the user submit all his data in the same token validation interval. `submissions.tasks` could be improved as suggested by scrutinizer

**Describe alternatives you've considered**
The parallel submission could be ignored for the moment, since we are able to submit about 2 samples/sec and it could be acceptable to receive a mail to generate a new token in order to complete the submission for a few thousands of samples

**Additional context**
Those will be ideally the things that need to be addressed by this issue:
- [x] `submission.tasks` refactoring as suggested by [scrutinizer](https://scrutinizer-ci.com/g/cnr-ibba/IMAGE-InjectTool/code-structure/master/py-module/biosample.tasks)
- [x] remove the `biosample_submission_id` attribute of `image_app.models.Submission` class. USI submission will be modeled in `biosample.models`
- [x] model new models in `biosample.models` (track here all USI submission? how I can patch a sample without searching USI data?)
- [x] Write a `SubmissionBacth` class to deal with a single submission batch (could be called in `chords`?)
- [x] Write a `SubmissionTask` to deal with an entire submission using `SubmissionBatch`
- [x] model batch size as a parameter - how I could divide objects? could related objects belong to distinct batches?
- [x] refactor FetchStatus task accordingly with new modules
- [ ] model `biosample.management.commands` tests
- [x] mock and test things as usual
- [x] delete old-modules 
- [x] refactor code and place things in their appropriate module
- [x] test a biosample submission with a small batch size
- [ ] model relationship between animals
- [x] generate fake submission data using `Faker`
- [x] test a big submission using batches
- [x] check documentation

**Comment by wizardfan** [comment]
the key could be to maintain the relationship
rough thought:
only for related animals and samples, unrelated records could be simply split
two scenarios
1) few animals and much more samples: animals first, then split samples
2) roughly equal number of animals and samples: treat related animal and records as units then split
