### ISSUE TITLE
Updating a biosample record still create a new biosample record

### ISSUE THREAD

**Issue by bunop** [cnr-ibba/IMAGE-InjectTool#8]
**Describe the bug**
After a successful biosample submission (and after retrieval of biosample ids), modifying and submitting data again will result in a new biosample record. The submission of an already submitted record shuold have the `accession` attribute inside JSON data. Relationship between sample and already submitted animal is not yet clear - should use the accession attribute? will InjectTool validation handle those changes? - wating for USI updated docs

**To Reproduce**
1. Complete a submission with success (get BioSamples ids and get the completed submission status through image InjectTool)
2. Update a sample and an animal (modify something in order to see NEED_REVISION status)
3. Pass the validation step
4. Provide a token and submit the updated data to biosample
5. Wait to get the submission complete.
6. Updated data will have a new biosample id (two biosample page for the same entity)

**Expected behavior**
Submitting the same data will update the same biosamples record. In biosamples page I will have the updated data and a note which tell me that data is updated

**Additional context**
We are facing issues in providing `accession` attribute in biosample data, the USI seems to have a problem managing updated data. Currently waiting for update from USI team

**Comment by wizardfan** [comment]
should be solved by ValidationTool version 2.0.2
