### ISSUE TITLE
add function to import from Template file

### ISSUE THREAD

**Issue by bunop** [cnr-ibba/IMAGE-InjectTool#9]
**Is your feature request related to a problem? Please describe.**
InjectTool lacks of the import Excel Template feature

**Describe the solution you'd like**
Loading InjectTool excel template file when starting a new submission

**Describe alternatives you've considered**
Template loading is a InjectTool requirement, and this type of data are difficult to convert in other input format like cryoweb or crbanim template file

**Additional context**
Those are the point that need to be addressed to upload excel file:
- [x] fix last UID columns `Sample.physiological_stage`, `Sample.preparation_interval`
- [x] decide how to map columns into UID
- [x] deal with provided ontologies (don't trust and discard)
- [x] start a new template application
- [x] parse a text like "3 years" in an a `time_unit` field
- [x] write down `helpers` module to define relations between objects and fill UID
- [x] write `tasks` method to upload data asynchronously
- [x] model language relation like `cryoweb` and `crbanim` applications
- [x] test stuff works and coverage remain nearly the same
- [x] remove check from create submission form and support template loading as a valid option 
- [x] refactor common create stuff as `image_app.helpers` functions
- [x] update docs

**Comment by wizardfan** [comment]
template file has been generated automatically from ruleset
